import React from 'react';

import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import play from '@/typography';
import ThemeRegistry from '@/app/ThemeRegistry';
import ReduxProvider from '@/components/ReduxProvider';
import FavoritesDrawer from '@/components/FavoritesDrawer';

export const metadata: Metadata = {
  title: 'Ecommerce App',
  description: 'Generated by create next app',
};

/**
 * use next Image instead of img tag
 * **/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={play.className}>
        <ThemeRegistry options={{ key: 'mui' }}>
          <main>
            <ReduxProvider>
              <Header />
              <FavoritesDrawer />
            </ReduxProvider>
            <section>{children}</section>
          </main>
        </ThemeRegistry>
      </body>
    </html>
  );
}
