import React from 'react';

import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import play from '@/typography';
import { ThemeProvider } from '@mui/material';
import theme from '@/mui.config';
import ThemeRegistry from '@/app/ThemeRegistry';

export const metadata: Metadata = {
  title: 'Ecommerce App',
  description: 'Generated by create next app',
};

/**
 * use next Image instead of img tag
 * **/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log('root layout');

  return (
    <html lang="en">
      <body className={play.className}>
        <ThemeRegistry options={{ key: 'mui' }}>
          <main>
            <Header />
            <section>{children}</section>
          </main>
        </ThemeRegistry>
      </body>
    </html>
  );
}
