import React from 'react';

import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import { Play } from 'next/font/google';

const tiltNeon = Play({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Ecommerce App',
  description: 'Generated by create next app',
};

/**
 * use next Image instead of img tag
 * **/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log('root layout');

  return (
    <html lang="en">
      <body className={tiltNeon.className}>
        <main>
          <Header />
          <section>{children}</section>
        </main>
      </body>
    </html>
  );
}
